name: brushGS
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.6
  - plyfile
  - python=3.7.13
  - pip=22.3.1
  - pytorch=1.12.1
  - torchvision=0.13.1
  - scikit-learn=1.0.2
  - tqdm
  - pip:
    - brush-gaussian-rasterization/
    - opencv-python
    - joblib